name: Make Commits

on:
  schedule:
    - cron: '30 11 * * *' # run 11:30 UTC every day
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.12' 
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python welcome.py
       
